version: "3.8"
services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: nest-blog
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:123@db:5432/nestdb"
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:prod

volumes:
  pgdata:
